### PR TITLE
Release 1.7.1

### PR DESCRIPTION
**Pull request by ChenTanyi**

### CODE REVIEW

**Comment by ChenTanyi** [comment]
It seems I cannot release the client-runtime, with conflicting profileId error

**Comment by yaohaizh** [comment]
@ChenTanyi , the update version is similar to the fluent premium using bundler tools

**Comment by ChenTanyi** [comment]
@yaohaizh Yeah, I've published it using fluent flow, but it failed. I would try again.

**Comment by ChenTanyi** [comment]
client-runtime-1.7.1 has a conflicting profileId [66eef5eb9b85bd] from other pom files in this release which have a profileId of [534d15ee3800f4]. Please split the pom files up by profileId (which is based on groupId).

Does it seem that the client-runtime jar should not be publish along with others?

**Comment by jianghaolu** [comment]
Yes. client-runtime's pom file and 3 jars need to be moved to a different folder and run the release pipeline separately.

**Comment by ChenTanyi** [comment]
@jianghaolu Could you give me the steps for release?
Does it:
1. remove the client-runtime in root pom and run original release pipeline
2. add client-runtime and remove others in root pom and run release pipeline again?

**Comment by jianghaolu** [comment]
Yes one release can only handle one group id

**Comment by ChenTanyi** [comment]
@jianghaolu I finally cannot publish it. Publish to staging but it is only the pom (like fluent 1.27.1). It seems hard to control the bundler.
Could you please release 1.7.1 in your working time? Thanks!

**Comment by jianghaolu** [comment]
You don't change the files. Just move client-runtime-1.7.1.pom, client-runtime-1.7.1.jar, client-runtime-1.7.1-sources.jar, client-runtime-1.7.1-javadoc.jar to a separate folder like this

folder1/
  client-runtime pom and 3 jars
folder2/
  the parent pom
  the other poms and corresponding jars

**Comment by jianghaolu** [comment]
You can follow the examples in previous releases too.

**Comment by jianghaolu** [comment]
I'm looking at your 1.7.1 folder and it seems like you accidentally included the SNAPSHOT files too.

**Pull request merged**
